server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
      show-sql: ${SPRING_JPA_PROPERTIES_SHOW_SQL}

auth:
  whitelisted-emails: ${AUTH_WHITELISTED_EMAILS}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    buckets:
      blog: ${AWS_S3_BUCKETS_BLOG}

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    expiration: ${SECURITY_JWT_EXPIRATION}
  cors:
    allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS}
    allowed-methods: ${SECURITY_CORS_ALLOWED_METHODS}
    allowed-headers: ${SECURITY_CORS_ALLOWED_HEADERS}
    exposed-headers: ${SECURITY_CORS_EXPOSED_HEADERS}
