spring:
  datasource:
    url: jdbc:h2://mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

auth:
  whitelisted-emails: "test@mail.com"

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: us-east-2
  s3:
    buckets:
      blog: personal-website-api-bucket-test

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    expiration: 604800000
  cors:
    allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS}
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Authorization,Content-Type"
    exposed-headers: "Authorization,Content-Type"
