server:
  port: 8080

spring:
  application:
    name: personal-website-api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

auth:
  whitelisted-emails: ${AUTH_WHITELISTED_EMAILS}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: us-east-2
  s3:
    buckets:
      blog: ${AWS_S3_BUCKETS_BLOG}

security:
  jwt:
    secret-key: ${SECURITY_JWT_SECRET_KEY}
    expiration: 604800000
  cors:
    allowed-origins: ${SECURITY_CORS_ALLOWED_ORIGINS}
    allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
    allowed-headers: "Authorization,Content-Type"
    exposed-headers: "Authorization,Content-Type"

management:
  endpoints:
    web:
      exposure:
        include: ["prometheus"]
