server:
  port: 8080

spring:
  application:
    name: apigw
  cloud:
    gateway:
      routes:
        - id: post
          uri: lb://POST
          predicates:
            - Path=/api/v1/post/**
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"