services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  api:
    container_name: api
    image: michaelyi/personal-website-api:latest
    depends_on:
      - postgres
