apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin 
spec:
  selector:
    matchLabels:
      app: admin 
  template:
    metadata:
      labels:
        app: admin 
    spec:
      containers:
      - name: admin 
        image: michaelyi/personal-website-admin:latest 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 

---
apiVersion: v1
kind: Service
metadata:
  name: admin 
spec:
  type: NodePort
  selector:
    app: admin 
  ports:
  - port: 80 
    targetPort: 80