version: "1.0.0"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5433"
    expose:
      - "5433"
    command: -p 5433
    # networks:
    #   - postgres
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

 api:
   image: michaelyi/personal-website-api:1.0.0
   container_name: api
   environment:
     - SPRING_PROFILES_ACTIVE=dev
   ports:
     - "8080:8080"
   depends_on:
     - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
