name: api-ci

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Create application.properties for Integration Tests
        run: |
          touch ./api/src/main/resources/application.properties
          echo "auth.whitelisted-emails=${{ secrets.API_AUTH_WHITELISTED_EMAILS }}" >> ./api/src/main/resources/application.properties
          echo "aws.access-key=${{ secrets.API_AWS_ACCESS_KEY }}" >> ./api/src/main/resources/application.properties
          echo "aws.secret-key=${{ secrets.API_AWS_SECRET_KEY }}" >> ./api/src/main/resources/application.properties
          echo "aws.s3.bucket=personal-website-api-bucket-test" >> ./api/src/main/resources/application.properties
          echo "security.cors.allowed-origins=${{ secrets.API_SECURITY_CORS_ALLOWED_ORIGINS }}" >> ./api/src/main/resources/application.properties
          echo "security.jwt.secret-key=${{ secrets.API_SECURITY_JWT_SECRET_KEY }}" >> ./api/src/main/resources/application.properties
          echo "spring.application.name=personal-website-api" >> ./api/src/main/resources/application.properties
          echo "spring.datasource.url=${{ secrets.API_SPRING_TEST_DATASOURCE_URL }}" >> ./api/src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.API_SPRING_DATASOURCE_USERNAME }}" >> ./api/src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.API_SPRING_DATASOURCE_PASSWORD }}" >> ./api/src/main/resources/application.properties
          echo "spring.jpa.hibernate.ddl-auto=update" >> ./api/src/main/resources/application.properties
          echo "spring.cache.type=redis" >> ./api/src/main/resources/application.properties
          echo "spring.cache.redis.time-to-live=900000" >> ./api/src/main/resources/application.properties
          echo "spring.data.redis.host=${{ secrets.API_SPRING_CACHE_HOST }}" >> ./api/src/main/resources/application.properties
          echo "spring.data.redis.port=6379" >> ./api/src/main/resources/application.properties
          echo "spring.data.redis.password=${{ secrets.API_SPRING_DATA_REDIS_PASSWORD }}" >> ./api/src/main/resources/application.properties

      - name: Create application-it.properties
        run: |
          touch ./api/src/test/resources/application-it.properties
          echo "auth.whitelisted-emails=test@mail.com" >> ./api/src/test/resources/application-it.properties
          echo "aws.access-key=${{ secrets.API_AWS_ACCESS_KEY }}" >> ./api/src/test/resources/application-it.properties
          echo "aws.secret-key=${{ secrets.API_AWS_SECRET_KEY }}" >> ./api/src/test/resources/application-it.properties
          echo "aws.s3.bucket=personal-website-api-bucket-test" >> ./api/src/test/resources/application-it.properties
          echo "security.cors.allowed-origins=*" >> ./api/src/test/resources/application-it.properties
          echo "security.jwt.secret-key=${{ secrets.API_SECURITY_JWT_SECRET_KEY }}" >> ./api/src/test/resources/application-it.properties
          echo "spring.application.name=personal-website-api" >> ./api/src/test/resources/application-it.properties
          echo "spring.datasource.url=${{ secrets.API_SPRING_TEST_DATASOURCE_URL }}" >> ./api/src/test/resources/application-it.properties
          echo "spring.datasource.username=${{ secrets.API_SPRING_DATASOURCE_USERNAME }}" >> ./api/src/test/resources/application-it.properties
          echo "spring.datasource.password=${{ secrets.API_SPRING_DATASOURCE_PASSWORD }}" >> ./api/src/test/resources/application-it.properties
          echo "spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver" >> ./api/src/test/resources/application-it.properties
          echo "spring.jpa.hibernate.ddl-auto=create-drop" >> ./api/src/test/resources/application-it.properties
          echo "spring.cache.type=redis" >> ./api/src/test/resources/application-it.properties
          echo "spring.cache.redis.time-to-live=900000" >> ./api/src/test/resources/application-it.properties
          echo "spring.data.redis.host=${{ secrets.API_TEST_SPRING_CACHE_HOST }}" >> ./api/src/test/resources/application-it.properties
          echo "spring.data.redis.port=6379" >> ./api/src/test/resources/application-it.properties

      - name: Build & Test API
        working-directory: ./api
        run: docker build .
