name: api-ci 

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Create New Properties File
        run: touch ./api/src/test/resources/application-it.properties

      - name: Update Properties File for Integration Tests 
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './api/src/test/resources/application-it.properties'
          property: |
            'auth.whitelisted-emails'
            'aws.access-key'
            'aws.secret-key'
            'aws.region'
            'aws.s3.buckets.blog'
            'security.jwt.secret-key'
            'security.jwt.expiration'
            'security.cors.allowed-origins'
            'security.cors.allowed-methods'
            'security.cors.allowed-headers'
            'security.cors.exposed-headers'
            'spring.application.name'
            'spring.datasource.url'
            'spring.datasource.username'
            'spring.datasource.password'
            'spring.datasource.driver-class-name'
            'spring.jpa.hibernate.ddl-auto'
            'spring.jpa.properties.hibernate.dialect'
          value: |
            '"test@mail.com"'
            '${{ secrets.API_AWS_ACCESS_KEY }}'
            '${{ secrets.API_AWS_SECRET_KEY }}'
            'us-east-2'
            'personal-website-api-bucket-test'
            '${{ secrets.API_SECURITY_JWT_SECRET_KEY }}'
            '604800000'
            '"*"'
            '"GET,POST,PUT,DELETE,OPTIONS"'
            '"Authorization,Content-Type"'
            '"Authorization,Content-Type"'
            'personal-website-api'
            '${{ secrets.API_SPRING_TEST_DATASOURCE_URL }}'
            '${{ secrets.API_SPRING_DATASOURCE_USERNAME }}'
            '${{ secrets.API_SPRING_DATASOURCE_PASSWORD }}'
            'org.postgresql.Driver'
            'update'
            'org.hibernate.dialect.PostgreSQLDialect'

      - name: Build & Test API 
        working-directory: ./api
        run: docker build . -t michaelyi/personal-website-api:latest