name: api-ci 

on:
  pull_request:
    paths:
      - apps/api/**

jobs:
  api-ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    defaults:
      run:
        working-directory: apps/api

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK v17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          
      - name: Package API 
        run: mvn clean package

      - name: Run Checkstyle on API 
        run: mvn validate

      - name: Run Unit and Integration Tests on API 
        run: mvn test