name: backend-ci

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        working-directory: ./backend/java
        run: ./gradlew clean bootJar --info

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Setup env
        run: |
          echo "PERSONAL_WEBSITE_AWS_ACCESS_KEY=${{ secrets.API_AWS_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_AWS_SECRET_KEY=${{ secrets.API_AWS_SECRET_KEY }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_AWS_S3_BUCKET=${{ secrets.API_AWS_S3_BUCKET }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_SPRING_DATASOURCE_URL=${{ secrets.API_SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_SPRING_DATASOURCE_USERNAME=${{ secrets.API_SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_SPRING_DATASOURCE_PASSWORD=${{ secrets.API_SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_SPRING_DATA_REDIS_HOST=${{ secrets.API_SPRING_DATA_REDIS_HOST }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_SPRING_DATA_REDIS_PASSWORD=${{ secrets.API_SPRING_DATA_REDIS_PASSWORD }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_SECURITY_AUTH_ADMIN_PW=${{ secrets.API_SECURITY_AUTH_ADMIN_PW }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_SECURITY_JWT_SECRET_KEY=${{ secrets.API_SECURITY_JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "PERSONAL_WEBSITE_TEST_SECURITY_AUTH_ADMIN_PW=${{ secrets.API_TEST_SECURITY_AUTH_ADMIN_PW }}" >> $GITHUB_ENV

      - name: Test
        working-directory: ./backend/java
        run: ./gradlew check --info
