name: backend-ci

on:
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        working-directory: ./backend/java
        run: ./gradlew clean bootJar --info

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Test
        working-directory: ./backend/java
        env:
          PERSONAL_WEBSITE_AWS_ACCESS_KEY: ${{ secrets.API_AWS_ACCESS_KEY }}
          PERSONAL_WEBSITE_AWS_SECRET_KEY: ${{ secrets.API_AWS_SECRET_KEY }}
          PERSONAL_WEBSITE_AWS_S3_BUCKET: ${{ secrets.API_AWS_S3_BUCKET }}
          PERSONAL_WEBSITE_SPRING_DATASOURCE_URL: ${{ secrets.API_SPRING_DATASOURCE_URL }}
          PERSONAL_WEBSITE_SPRING_DATASOURCE_USERNAME: ${{ secrets.API_SPRING_DATASOURCE_USERNAME }}
          PERSONAL_WEBSITE_SPRING_DATASOURCE_PASSWORD: ${{ secrets.API_SPRING_DATASOURCE_PASSWORD }}
          PERSONAL_WEBSITE_SPRING_DATA_REDIS_HOST: ${{ secrets.API_SPRING_DATA_REDIS_HOST }}
          PERSONAL_WEBSITE_SPRING_DATA_REDIS_PASSWORD: ${{ secrets.API_SPRING_DATA_REDIS_PASSWORD }}
          PERSONAL_WEBSITE_SECURITY_AUTH_ADMIN_PW: ${{ secrets.API_SECURITY_AUTH_ADMIN_PW }}
          PERSONAL_WEBSITE_SECURITY_JWT_SECRET_KEY: ${{ secrets.API_SECURITY_JWT_SECRET_KEY }}
          PERSONAL_WEBSITE_TEST_SECURITY_AUTH_ADMIN_PW: ${{ secrets.API_TEST_SECURITY_AUTH_ADMIN_PW }}
        run: ./gradlew check --info
