name: backend-cd

on:
  push:
    branches:
      - prod

permissions:
  contents: read
  packages: write

env:
  VERSION: 2.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        working-directory: ./backend
        run: ./gradlew clean bootJar --info

      - name: Archive .jar File 
        uses: actions/upload-artifact@v4
        with:
          name: app.jar 
          path: ./backend/build/libs/backend-${{ env.VERSION }}.jar

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download .jar File 
        uses: actions/download-artifact@v4
        with:
          name: app.jar 
          path: ./backend/build/libs/

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        working-directory: ./backend
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          docker build . -t michaelyi/personal-website-api:latest
          docker build . -t michaelyi/personal-website-api:${{ env.VERSION }}
          docker push michaelyi/personal-website-api:latest
          docker push michaelyi/personal-website-api:${{ env.VERSION }}
          echo "$SSH_PRIVATE_KEY" > personal-website-api-kp.pem
          chmod 400 personal-website-api-kp.pem
          ssh -o StrictHostKeyChecking=no -i personal-website-api-kp.pem ec2-user@${SSH_HOST} '
            sudo docker stop personal-website-api || true
            sudo docker rm personal-website-api || true
            sudo docker rmi -f $(sudo docker image ls -a -q)
            sudo docker pull michaelyi/personal-website-api:latest
            sudo docker run --name personal-website-api -d -p 8080:8080 \
              -e SPRING_APPLICATION_NAME=personal-website-api \
              -e SPRING_APPLICATION_VERSION=${{ env.VERSION }} \
              -e AWS_ACCESS_KEY=${{ secrets.API_AWS_ACCESS_KEY }} \
              -e AWS_SECRET_KEY=${{ secrets.API_AWS_SECRET_KEY }} \
              -e AWS_S3_BUCKET=${{ secrets.API_AWS_S3_BUCKET }} \
              -e SPRING_DATASOURCE_URL=${{ secrets.API_SPRING_DATASOURCE_URL }} \
              -e SPRING_DATASOURCE_USERNAME=${{ secrets.API_SPRING_DATASOURCE_USERNAME }} \
              -e SPRING_DATASOURCE_PASSWORD=${{ secrets.API_SPRING_DATASOURCE_PASSWORD }} \
              -e SPRING_JPA_HIBERNATE_DDL_AUTO=validate \
              -e SPRING_DATA_REDIS_HOST=${{ secrets.API_SPRING_DATA_REDIS_HOST }} \
              -e SPRING_DATA_REDIS_PORT=6379 \
              -e SPRING_DATA_REDIS_PASSWORD=${{ secrets.API_SPRING_DATA_REDIS_PASSWORD }} \
              -e SECURITY_AUTH_ADMIN_PW=${{ secrets.API_SECURITY_AUTH_ADMIN_PW }} \
              -e SECURITY_CORS_ALLOWED_ORIGINS=https://michael-yi.com,https://admin.michael-yi.com \
              -e SECURITY_JWT_SECRET_KEY=${{ secrets.API_SECURITY_JWT_SECRET_KEY }} \
              -e SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=10MB \
              -e SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=10MB \
              michaelyi/personal-website-api:latest
            '
