name: cd

on:
  push:
    branches:
      - prod

permissions:
  contents: read
  packages: write

env:
  VERSION: 2.1.3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        working-directory: ./backend/java
        run: ./gradlew clean bootJar --info

      - name: Archive .jar File 
        uses: actions/upload-artifact@v4
        with:
          name: app.jar 
          path: ./backend/java/build/libs/java-${{ env.VERSION }}.jar

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - ses: actions/checkout@v4
      - name: Download .jar File 
        uses: actions/download-artifact@v4
        with:
          name: app.jar 
          path: ./backend/java/build/libs/

      - name: Deploy
        working-directory: ./backend/java
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "$SSH_KEY" > key.pem
	  chmod 400 key.pem
          ssh -i key.pem root@${SSH_HOST} "kill $(lsof -t -i:80) rm app.jar"
	  scp -i key.pem ./build/libs/app.jar ubuntu@${SSH_HOST}:~
          ssh key.pem root@${SSH_HOST} "java -jar app.jar"

