name: cd

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5

      - name: Setup zip
        uses: montudor/action-zip@v1

      - name: Build
        run: |
          go build -o app

      - name: Zip Build
        run: |
          zip -r app.zip pages static app index.html

      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app.zip

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Build 
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > key.pem
          chmod 400 key.pem
          ssh -i key.pem root@${SSH_HOST} '
            tmux kill-server
            rm -rf -f pages 
            rm -rf -f static
            rm -f index.html 
            rm -f app
          '
          scp -i key.pem app.zip root@${SSH_HOST}:~
          ssh -i key.pem root@${SSH_HOST} '
            unzip -o app.zip
            rm app.zip
            tmux new -d -s app "./app"
          '