name: cd

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  VERSION: 5.3.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go v1.21.x
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Setup zip
        uses: montudor/action-zip@v1

      - name: Build Web Server
        working-directory: ./frontend/main
        run: |
          go build -o app server.go

      - name: Zip Static Assets & Executable
        working-directory: ./frontend/main
        run: |
          rm server.go
          zip -r app.zip .
          mv app.zip ../../app.zip

      - name: Archive Static Assets
        uses: actions/upload-artifact@v4
        with:
          name: main 
          path: ./app.zip

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Static Assets + Executable
        uses: actions/download-artifact@v4
        with:
          name: main 
          path: .

      - name: Deploy
        env:
          FRONTEND_SSH_HOST: ${{ secrets.FRONTEND_SSH_HOST }}
          FRONTEND_SSH_KEY: ${{ secrets.FRONTEND_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${FRONTEND_SSH_HOST} >> ~/.ssh/known_hosts
          echo "$FRONTEND_SSH_KEY" > key.pem
          chmod 400 key.pem
          ssh -i key.pem root@${FRONTEND_SSH_HOST} '
            tmux kill-server
            rm -rf -f pages 
            rm -rf -f static
            rm -f app
          '
          scp -i key.pem app.zip root@${FRONTEND_SSH_HOST}:~
          ssh -i key.pem root@${FRONTEND_SSH_HOST} '
            unzip -o app.zip
            rm app.zip
            tmux new -d -s app "./app"
          '
