name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: |
          mvn package
          mv target/personalwebsite-*.jar app.jar

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app.jar

  deploy:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Build 
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
          echo "$SSH_KEY" > key.pem
          chmod 400 key.pem

          ssh -i key.pem root@${SSH_HOST} '
            tmux kill-server
            rm -f app.jar 
          '

          scp -i key.pem app.jar root@${SSH_HOST}:./

          ssh -i key.pem root@${SSH_HOST} '
            tmux new -d -s app "java -jar app.jar"
          '