name: deploy

on:
  push:
    branches: ["prod"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
      - uses: docker/login-action@v3
      - uses: oven-sh/setup-bun@v1

      - name: Set up JDK 17
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        working-directory: ./api
        run: mvn clean package

      - name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the Docker image
        working-directory: ./api
        run: |
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest

      - name: Install Bun to Format, Lint, and Build Client
        working-directory: ./client
        run: |
          bun install
          bun format
          bun lint
          bun run build
