name: e2e-tests

on:
  pull_request:
    branches: [ prod, dev ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        working-directory: ./web
        with:
          build: npm i && npm run build
          start: npm start
