name: cd

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  VERSION: 5.3.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Zip Static Assets
        working-directory: ./frontend
        uses: montudor/action-zip@v1
        with:
          args: zip -r -j app.zip main

      - name: Archive Static Assets + Executable
        uses: actions/upload-artifact@v4
        with:
          name: main 
          path: ./app.zip

  deploy:
    needs: build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Static Assets + Executable
        uses: actions/download-artifact@v4
        with:
          name: main 
          path: .

      - name: Deploy
        env:
          FRONTEND_SSH_HOST: ${{ secrets.FRONTEND_SSH_HOST }}
          FRONTEND_SSH_KEY: ${{ secrets.FRONTEND_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${FRONTEND_SSH_HOST} >> ~/.ssh/known_hosts
          echo "$FRONTEND_SSH_KEY" > key.pem
          chmod 400 key.pem
          scp -i key.pem app.zip root@${FRONTEND_SSH_HOST}:~
          ssh -i key.pem root@${FRONTEND_SSH_HOST} '
            cd /var/www/html
            rm -rf *

            mv ~/app.zip app.zip
            unzip -o app.zip
            rm app.zip
            rm server.go
          '
