name: frontend-admin

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Build & Test
        working-directory: ./frontend/admin
        run: |
          npm ci
          npm run build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
    permissions:
      contents: read
      packages: write
    env:
      VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Deploy
        uses: docker/login-action@v3
        working-directory: ./frontend/admin
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker build . -t michaelyi/personal-website-admin:latest
          docker build . -t michaelyi/personal-website-admin:${{ env.VERSION }}
          docker push michaelyi/personal-website-admin:latest
          docker push michaelyi/personal-website-admin:${{ env.VERSION }}