name: frontend-admin-cd

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION: 1.0.0

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
        
      - name: Deploy
        working-directory: ./frontend/admin
        uses: docker/login-action@v3
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          npm ci
          npm run build
          docker build . -t michaelyi/personal-website-admin:latest
          docker build . -t michaelyi/personal-website-admin:${{ env.VERSION }}
          docker push michaelyi/personal-website-admin:latest
          docker push michaelyi/personal-website-admin:${{ env.VERSION }}