name: frontend-admin-ci

on:
  pull_request:
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Build
        working-directory: ./frontend/admin
        run: |
          npm ci
          npm run build
