name: frontend-web-cd

on:
  push:
    branches:
      - prod

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      VERSION: 5.0.6

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Build 
        working-directory: ./frontend/web
        run: |
          npm ci
          npm run build
    
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        working-directory: ./frontend/web
        run: |
          docker build . -t michaelyi/personal-website-web:latest
          docker build . -t michaelyi/personal-website-web:${{ env.VERSION }}
          docker push michaelyi/personal-website-web:latest
          docker push michaelyi/personal-website-web:${{ env.VERSION }}
