name: frontend-web-cd

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION: 5.0.2

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy
        working-directory: ./frontend/web
        run: |
          npm ci
          npm run build
          docker build . -t michaelyi/personal-website-web:latest
          docker build . -t michaelyi/personal-website-web:${{ env.VERSION }}
          docker push michaelyi/personal-website-web:latest
          docker push michaelyi/personal-website-web:${{ env.VERSION }}