name: pr

on:
  pull_request:
    branches: ["prod", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Lint and Build Backend API with Maven
        working-directory: ./api
        run: |
          mvn validate
          mvn clean package

      - name: Lint and Build Frontend Client with Bun
        run: |
          bun install
          bun lint
          cd client
          bun install
          bun lint
          bun run build
