name: pr

on:
  pull_request:
    branches: ["prod", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Build with Maven
        working-directory: ./api
        run: mvn clean package
