name: web-cd

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      VERSION: 5.0.0

    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: michaelyi
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, Test, Deploy API
        working-directory: ./web
        run: |
          docker build . -t michaelyi/personal-website-web:${{ env.VERSION }}
          docker push michaelyi/personal-website-web:${{ env.VERSION }}