name: web-ci

on:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Build & Test Admin Platform 
        working-directory: ./web
        run: docker build .
